Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2022
Var
A, B : inteiro

Inicio
escreva("Numero A? ")
 leia(A)
 escreva("Numero B? ")
 leia(B)
 escreval ("A multiplicação dos numeros digitados é: ", A*B)


Fimalgoritmo