Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2022
Var
 numeroA, numeroB : inteiro

Inicio
escreva("Numero A? ")
 leia(numeroA)
 escreva("Numero B? ")
 leia(numeroB)
 escreva("Soma A - B = ", numeroA - numeroB)


Fimalgoritmo